spring:
  application:
    name: dglue-admin
  datasource:
    druid:
      url: jdbc:mysql://192.168.1.13:3308/xxl-glue?useUnicode=true&characterEncoding=GBK
      username: tbj
      password: tbj900900
      filters: stat
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'X'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      driver-class-name: com.mysql.jdbc.Driver

logging:
  config: classpath:logback-boot.xml
  file: /Users/jierui/Downloads/dglue.log
  path: /Users/jierui/Downloads/logs

mybatis:
  mapper-locations: classpath*:mybatis-mapper/*mapper.xml
  type-aliases-package: com.ars.dglue.admin.model
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: null
